version: '3'
services:


  #######################################################################
  #################### yoursmartchef.com ################################
  #######################################################################

  #NodeJS Service
  yoursmartchef_com_nodejs:
    build:
      context: .
      dockerfile: ./yoursmartchef.com/docker/nodejs/Dockerfile
    container_name: "${DOCKER_PREFIX}-yoursmartchef-nodejs"
    depends_on:
      - yoursmartchef_com_web
    volumes:
      - ./yoursmartchef.com/:/var/www/
    networks:
      - app-network

  #######################################################################
  #################### yourpersonalchief.com ################################
  #######################################################################

  #NodeJS Service
  yourpersonalchief_com_nodejs:
    build:
      context: .
      dockerfile: ./yourpersonalchief.com/docker/nodejs/Dockerfile
    container_name: "${DOCKER_PREFIX}-yourpersonalchief-nodejs"
    depends_on:
      - yourpersonalchief_com_web
    volumes:
      - ./yourpersonalchief.com/:/var/www/
    networks:
      - app-network


  #######################################################################
  #################### yourperfectfood.com ################################
  #######################################################################

  #NodeJS Service
  yourperfectfood_com_nodejs:
    build:
      context: .
      dockerfile: ./yourperfectfood.com/docker/nodejs/Dockerfile
    container_name: "${DOCKER_PREFIX}-yourperfectfood-nodejs"
    depends_on:
      - yourperfectfood_com_web
    volumes:
      - ./yourperfectfood.com/:/var/www/
    networks:
      - app-network


  #######################################################################
  #################### inspireforcooking.com ################################
  #######################################################################

  #NodeJS Service
  inspireforcooking_com_nodejs:
    build:
      context: .
      dockerfile: ./inspireforcooking.com/docker/nodejs/Dockerfile
    container_name: "${DOCKER_PREFIX}-inspireforcooking-nodejs"
    depends_on:
      - inspireforcooking_com_web
    volumes:
      - ./inspireforcooking.com/:/var/www/
    networks:
      - app-network


  #######################################################################
  #################### findyourfoodstyle.com ################################
  #######################################################################

  #NodeJS Service
  findyourfoodstyle_com_nodejs:
    build:
      context: .
      dockerfile: ./findyourfoodstyle.com/docker/nodejs/Dockerfile
    container_name: "${DOCKER_PREFIX}-findyourfoodstyle-nodejs"
    depends_on:
      - findyourfoodstyle_com_web
    volumes:
      - ./findyourfoodstyle.com/:/var/www/
    networks:
      - app-network


  #Nginx Service
  webserver:
    image: nginx:alpine
    container_name: "${DOCKER_PREFIX}-webserver"
    restart: unless-stopped
    tty: true
    depends_on:
      - yoursmartchef_com_web
      - yourpersonalchief_com_web
      - yourperfectfood_com_web
      - inspireforcooking_com_web
      - findyourfoodstyle_com_web
    ports:
      - "80:80"
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf

      - ./yoursmartchef.com/:/var/www/yoursmartchef.com/
      - ./yoursmartchef.com/docker/nginx/local.conf:/etc/nginx/conf.d/yoursmartchef.conf

      - ./yourpersonalchief.com/:/var/www/yourpersonalchief.com/
      - ./yourpersonalchief.com/docker/nginx/local.conf:/etc/nginx/conf.d/yourpersonalchief.conf

      - ./yourperfectfood.com/:/var/www/yourperfectfood.com/
      - ./yourperfectfood.com/docker/nginx/local.conf:/etc/nginx/conf.d/yourperfectfood.conf

      - ./inspireforcooking.com/:/var/www/inspireforcooking.com/
      - ./inspireforcooking.com/docker/nginx/local.conf:/etc/nginx/conf.d/inspireforcooking.conf

      - ./findyourfoodstyle.com/:/var/www/findyourfoodstyle.com/
      - ./findyourfoodstyle.com/docker/nginx/local.conf:/etc/nginx/conf.d/findyourfoodstyle.conf
    networks:
      - app-network

  #######################################################################
  #######################   Services   ##################################
  #######################################################################

  #MySQL Service
  db:
    image: mysql:5.7
    container_name: "${DOCKER_PREFIX}-db"
    restart: unless-stopped
    tty: true
    #    command: --init-file /etc/mysql/init.sql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
    volumes:
      - dbdata:/var/lib/mysql/
      - ./docker/mysql/:/etc/mysql/
    networks:
      - app-network


#Docker Networks
networks:
  app-network:
    driver: bridge
#Volumes
volumes:
  dbdata:
    driver: local
