version: '3'
services:

#  ##############   WEB CONTAINERS   ##############

  #Nginx Service
  webserver:
    image: nginx:alpine
    container_name: "${DOCKER_PREFIX}-webserver"
    restart: unless-stopped
    tty: true
    depends_on:
      - yoursmartchef_com_web
      - yourpersonalchief_com_web
      - yourperfectfood_com_web
      - inspireforcooking_com_web
      - findyourfoodstyle_com_web
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf

      - ./yoursmartchef.com/:/var/www/yoursmartchef.com/
      - ./yoursmartchef.com/docker/nginx/yoursmartchef.conf:/etc/nginx/conf.d/yoursmartchef.conf

      - ./yourpersonalchief.com/:/var/www/yourpersonalchief.com/
      - ./yourpersonalchief.com/docker/nginx/yourpersonalchief.conf:/etc/nginx/conf.d/yourpersonalchief.conf

      - ./yourperfectfood.com/:/var/www/yourperfectfood.com/
      - ./yourperfectfood.com/docker/nginx/yourperfectfood.conf:/etc/nginx/conf.d/yourperfectfood.conf

      - ./inspireforcooking.com/:/var/www/inspireforcooking.com/
      - ./inspireforcooking.com/docker/nginx/inspireforcooking.conf:/etc/nginx/conf.d/inspireforcooking.conf

      - ./findyourfoodstyle.com/:/var/www/findyourfoodstyle.com/
      - ./findyourfoodstyle.com/docker/nginx/findyourfoodstyle.conf:/etc/nginx/conf.d/findyourfoodstyle.conf

      - /etc/letsencrypt:/etc/letsencrypt
    networks:
      - app-network


  #######################################################################
  #######################   Services   ##################################
  #######################################################################

  #MySQL Service
  db:
    image: mysql:5.7
    container_name: "${DOCKER_PREFIX}-db"
    restart: unless-stopped
    tty: true
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
    volumes:
      - dbdata:/var/lib/mysql/
      - ./docker/mysql/:/etc/mysql/
    networks:
      - app-network

#Docker Networks
networks:
  app-network:
    driver: bridge
#Volumes
volumes:
  dbdata:
    driver: local